const Products = [
  {
    id: 1,
    name: "Product 1",
    description: "Product 1 Description",
    price: 10.99,
  },
  {
    id: 2,
    name: "Product 2",
    description: "Product 2 Description",
    price: 20.99,
  },
  {
    id: 3,
    name: "Product 3",
    description: "Product 3 Description",
    price: 30.99,
  },
  {
    id: 4,
    name: "Product 4",
    description: "Product 4 Description",
    price: 40.99,
  },
  {
    id: 5,
    name: "Product 5",
    description: "Product 5 Description",
    price: 50.99,
  },
  {
    id: 6,
    name: "Product 6",
    description: "Product 6 Description",
    price: 15.99,
  },
  {
    id: 7,
    name: "Product 7",
    description: "Product 7 Description",
    price: 25.99,
  },
  {
    id: 8,
    name: "Product 8",
    description: "Product 8 Description",
    price: 35.99,
  },
  {
    id: 9,
    name: "Product 9",
    description: "Product 9 Description",
    price: 45.99,
  },
  {
    id: 10,
    name: "Product 10",
    description: "Product 10 Description",
    price: 55.99,
  },
  {
    id: 11,
    name: "Product 11",
    description: "Product 11 Description",
    price: 15.99,
  },
  {
    id: 12,
    name: "Product 12",
    description: "Product 12 Description",
    price: 25.99,
  },
  {
    id: 13,
    name: "Product 13",
    description: "Product 13 Description",
    price: 35.99,
  },
  {
    id: 14,
    name: "Product 14",
    description: "Product 14 Description",
    price: 45.99,
  },
  {
    id: 15,
    name: "Product 15",
    description: "Product 15 Description",
    price: 55.99,
  },
  {
    id: 16,
    name: "Product 16",
    description: "Product 16 Description",
    price: 15.99,
  },
  {
    id: 17,
    name: "Product 17",
    description: "Product 17 Description",
    price: 25.99,
  },
  {
    id: 18,
    name: "Product 18",
    description: "Product 18 Description",
    price: 35.99,
  },
  {
    id: 19,
    name: "Product 19",
    description: "Product 19 Description",
    price: 45.99,
  },
  {
    id: 20,
    name: "Product 20",
    description: "Product 20 Description",
    price: 55.99,
  },
  {
    id: 21,
    name: "Product 21",
    description: "Product 21 Description",
    price: 11.99,
  },
  {
    id: 22,
    name: "Product 22",
    description: "Product 22 Description",
    price: 22.99,
  },
  {
    id: 23,
    name: "Product 23",
    description: "Product 23 Description",
    price: 33.99,
  },
  {
    id: 24,
    name: "Product 24",
    description: "Product 24 Description",
    price: 44.99,
  },
  {
    id: 25,
    name: "Product 25",
    description: "Product 25 Description",
    price: 55.99,
  },
  {
    id: 26,
    name: "Product 26",
    description: "Product 26 Description",
    price: 16.99,
  },
  {
    id: 27,
    name: "Product 27",
    description: "Product 27 Description",
    price: 27.99,
  },
  {
    id: 28,
    name: "Product 28",
    description: "Product 28 Description",
    price: 38.99,
  },
  {
    id: 29,
    name: "Product 29",
    description: "Product 29 Description",
    price: 49.99,
  },
  {
    id: 30,
    name: "Product 30",
    description: "Product 30 Description",
    price: 53.99,
  },
  {
    id: 31,
    name: "Product 31",
    description: "Product 31 Description",
    price: 31.99,
  },
  {
    id: 32,
    name: "Product 32",
    description: "Product 32 Description",
    price: 32.99,
  },
]

export default Products
